// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/booking/booking.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// İstek Modeli (Request)
type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                 // Kim alıyor?
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`              // Hangi etkinlik?
	TicketCount   int32                  `protobuf:"varint,3,opt,name=ticket_count,json=ticketCount,proto3" json:"ticket_count,omitempty"` // Kaç bilet?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_api_proto_booking_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBookingRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateBookingRequest) GetTicketCount() int32 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

// Cevap Modeli (Response)
type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`          // Oluşan rezervasyon ID'si
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                 // Durum (SUCCESS, FAILED)
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Hata varsa detayı
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_api_proto_booking_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CreateBookingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateBookingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_booking_booking_proto protoreflect.FileDescriptor

const file_api_proto_booking_booking_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/booking/booking.proto\x12\abooking\"m\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12!\n" +
	"\fticket_count\x18\x03 \x01(\x05R\vticketCount\"s\n" +
	"\x15CreateBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2`\n" +
	"\x0eBookingService\x12N\n" +
	"\rCreateBooking\x12\x1d.booking.CreateBookingRequest\x1a\x1e.booking.CreateBookingResponseB5Z3github.com/keremkartal/goticketra/api/proto/bookingb\x06proto3"

var (
	file_api_proto_booking_booking_proto_rawDescOnce sync.Once
	file_api_proto_booking_booking_proto_rawDescData []byte
)

func file_api_proto_booking_booking_proto_rawDescGZIP() []byte {
	file_api_proto_booking_booking_proto_rawDescOnce.Do(func() {
		file_api_proto_booking_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_booking_booking_proto_rawDesc), len(file_api_proto_booking_booking_proto_rawDesc)))
	})
	return file_api_proto_booking_booking_proto_rawDescData
}

var file_api_proto_booking_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_booking_booking_proto_goTypes = []any{
	(*CreateBookingRequest)(nil),  // 0: booking.CreateBookingRequest
	(*CreateBookingResponse)(nil), // 1: booking.CreateBookingResponse
}
var file_api_proto_booking_booking_proto_depIdxs = []int32{
	0, // 0: booking.BookingService.CreateBooking:input_type -> booking.CreateBookingRequest
	1, // 1: booking.BookingService.CreateBooking:output_type -> booking.CreateBookingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_booking_booking_proto_init() }
func file_api_proto_booking_booking_proto_init() {
	if File_api_proto_booking_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_booking_booking_proto_rawDesc), len(file_api_proto_booking_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_booking_booking_proto_goTypes,
		DependencyIndexes: file_api_proto_booking_booking_proto_depIdxs,
		MessageInfos:      file_api_proto_booking_booking_proto_msgTypes,
	}.Build()
	File_api_proto_booking_booking_proto = out.File
	file_api_proto_booking_booking_proto_goTypes = nil
	file_api_proto_booking_booking_proto_depIdxs = nil
}
